### ISSUE TITLE
Cluster should be diskless

### ISSUE THREAD

**Issue by globalcitizen** [rusher81572/picluster#1]
PXE boot is far superior to manual installation of the OS on each node.

IMHO you should package this project a docker image with a PXE/DHCP/TFTP server, plus the apparently existing HTTP server, and let it autoconfigure the slaves for plug and play / autoscale.

**Comment by rusher81572** [comment]
Good idea, thanks for the feedback. I looked into making this as a Docker image but this app runs the Docker engine commands directly on the nodes and wont be able to communicate with the Docker engine from inside a container.

**Comment by globalcitizen** [comment]
> wont be able to communicate with the Docker engine from inside a container

Why not?

**Comment by rusher81572** [comment]
Do you know of a way? Please share if you do. Containers are isolated from the host where the Docker engine is running.

**Comment by globalcitizen** [comment]
## Situation one

OK if you mean "there is no way to usually communicate with the docker engine on the host (from a container it is running)" then maybe this is true by default. I don't know. I haven't used docker a lot recently. However, you could work around any such limitation by opening a port that was visible to the container on an interface that is visible to the container, eg. say docker usually listens on 127.0.0.1:12345, use iptables, netcat or some other TCP proxying approach to add a new port on 192.168.x.x:12345 that is visible to the container and simply redirects to 127.0.0.1:12345.

## Situation two
However... my understanding is that you have a docker engine running on each node in the cluster, and that each such node has its own control port. If that is the case, there is nothing to stop you firing up the OS that is fed to them via PXE so that the port is exposed to the master node on the network. I guess you may need to solve situation one as well if you also want the master node to host arbitrary workloads.

Hope that helps.

**Comment by CarltonSemple** [comment]
You can communicate with the host docker socket by adding /var/run/docker as a shared volume when doing `docker run`, and make sure to launch it as a privileged container

**Comment by rusher81572** [comment]
Closing this one for now since it is not a focus for this project right now.
