### ISSUE TITLE
node-waf configure build failed

### ISSUE THREAD

**Issue by lorenzo95** [rusher81572/picluster#15]
Hello, I am trying to build the server with the latest nodejs and it errors out at "node-waf configure build failed". Should I be using a specific node version for this? I am using 7.7.4 and npm 4.1.2.

failed at the microtime@0.2.0 install script node-waf configure build. 
Thank you

**Comment by rusher81572** [comment]
Hi there. Thanks for trying out PiCLuster.  I upgraded to 7.7.4 from 4.x and got the same error. 
```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
```

I have no idea what that means but PiCluster still worked for me:

```
rm -rf node_modules
npm install
node server.js
```

I can not find any details online about this.

**Comment by rusher81572** [comment]
@lorenzo95 does node server.js work for you anyway with that error?

**Comment by lorenzo95** [comment]
Ah, you are right. 
It throws the error on server and agent. The web server is fine. But as you said, everything still runs. I think the waf package is missing. It might need nodejs-dev which isn't available for me on 7. I only see it in version 4.2.6 in the repo. 

Got it to work in a two vm cluster. Didn't build the glusterfs yet. Will add another node and do some fail-over testing. Pretty cool stuff ;) Looking forward to playing with it more.

**Comment by rusher81572** [comment]
Great, glad that you got it working. If you have any questions of need help, please let me know. I do not recommend running Gluster inside Docker for production use, I had a few problems with it.
